services:
  ytdl-material:
    image: voc0der/ytdl-material:nightly
    restart: always
    ports:
      - "17442:17442"
    volumes:
      - ./appdata:/app/appdata
      - ./audio:/app/audio
      - ./video:/app/video
      - ./subscriptions:/app/subscriptions
      - ./users:/app/users
