services:
  ytdl-material:
    image: voc0der/ytdl-material:nightly
    container_name: ytdl-material
    restart: always
    environment:
      ytdl_use_local_db: 'false'
      ytdl_remote_db_type: 'postgres'
      ytdl_postgresdb_connection_string: 'postgresql://PlaceholderUser:PlaceholderPassword@ytdl-postgres-db:5432/PlaceholderDB'
      write_ytdl_config: 'true'
    depends_on:
      ytdl-postgres-db:
        condition: service_healthy
    ports:
      - "17442:17442"
    volumes:
      - ./appdata:/app/appdata
      - ./audio:/app/audio
      - ./video:/app/video
      - ./subscriptions:/app/subscriptions
      - ./users:/app/users

  ytdl-postgres-db:
    image: postgres:alpine
    container_name: ytdl-postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: PlaceholderPassword
      POSTGRES_DB: PlaceholderDB
      POSTGRES_USER: PlaceholderUser
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U PlaceholderUser -d PlaceholderDB"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 35s
      start_interval: 1s
    logging:
      driver: "none"
    volumes:
      - ./db:/var/lib/postgresql/data
